# Generated by Django 5.0.3 on 2024-04-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='elearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/files')),
                ('file', models.FileField(upload_to='uploads/files')),
                ('name', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
